### ISSUE TITLE
Question about the design

### ISSUE THREAD

**Issue by cirias** [wj-zhe/Kretstrad#1]
Hello,
I can only find the PCB file for the left half. I think it can be flipped to be the right half. But I'm confused about the circuits connecting the control board. It looks like all the pads in the same row are shorted. My guess is one have to manually cut the traces, and the way you cut them decide which half it will be. Am I correct about this? Is this common for split keyboard design? And how can this pass the Kicad rules checker without causing any violation?

Sorry about throwing so many questions to you. I'm trying to design my own keyboard and I saw yours. It inspires me so much! If you ever get a chance to take a look, it will mean a lot to me!

**Comment by cirias** [comment]
I just figured. The pad is actually a two pads connector after zoom in... No question now. But still want to appreciate you for the amazing project!

**Comment by wj-zhe** [comment]
Glad you figured it out. Feel free to contact me on any issue.
